# Generated by Django 3.1.5 on 2021-10-20 07:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=25, primary_key=True, serialize=False, unique=True)),
                ('code', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=1024, null=True)),
                ('created_by_username', models.CharField(default='not assigned', max_length=255)),
                ('updated_by_username', models.CharField(default='not assigned', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(blank=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('mymodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='server.mymodel')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            bases=('server.mymodel',),
        ),
        migrations.CreateModel(
            name='PaymentType',
            fields=[
                ('mymodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='server.mymodel')),
            ],
            bases=('server.mymodel',),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('mymodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='server.mymodel')),
                ('barcode', models.CharField(blank=True, max_length=25, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('inventory', models.IntegerField(default=0)),
                ('category_obj', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='server.category')),
            ],
            bases=('server.mymodel',),
        ),
        migrations.CreateModel(
            name='UserImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='hand')),
                ('updated_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('mymodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='server.mymodel')),
                ('received', models.FloatField(blank=True, null=True)),
                ('balance', models.FloatField(blank=True, null=True)),
                ('total', models.FloatField(blank=True, null=True)),
                ('is_adjust', models.BooleanField(default=False)),
                ('is_success', models.BooleanField(default=False)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='server.paymenttype')),
            ],
            bases=('server.mymodel',),
        ),
        migrations.CreateModel(
            name='SubTransaction',
            fields=[
                ('mymodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='server.mymodel')),
                ('n_item', models.IntegerField(default=1)),
                ('is_adjust', models.BooleanField(default=False)),
                ('price', models.FloatField(blank=True, null=True)),
                ('product_obj', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='server.product')),
                ('transaction_obj', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='server.transaction')),
            ],
            bases=('server.mymodel',),
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('mymodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='server.mymodel')),
                ('n_item', models.IntegerField()),
                ('price', models.FloatField()),
                ('product_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.product')),
            ],
            bases=('server.mymodel',),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('current_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='server.category')),
                ('current_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='server.transaction')),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('mymodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='server.mymodel')),
                ('barcode', models.CharField(blank=True, max_length=25, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('inventory', models.IntegerField(default=0)),
                ('n_item', models.IntegerField()),
                ('category_obj', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='server.category')),
                ('product_obj', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='server.product')),
            ],
            bases=('server.mymodel',),
        ),
        migrations.CreateModel(
            name='GroupingPromotion',
            fields=[
                ('mymodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='server.mymodel')),
                ('n_item', models.IntegerField()),
                ('price', models.FloatField()),
                ('products', models.ManyToManyField(to='server.Product')),
            ],
            bases=('server.mymodel',),
        ),
        migrations.CreateModel(
            name='ChangeProduct',
            fields=[
                ('mymodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='server.mymodel')),
                ('balance', models.FloatField()),
                ('new_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_product_new_product', to='server.product')),
                ('old_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_product_old_product', to='server.product')),
            ],
            bases=('server.mymodel',),
        ),
    ]
